name: Code Style

on:
  pull_request:
    branches: [ 'master', 'v2.0', 'v3.0' ]
  push:
    branches: [ 'master', 'v2.0', 'v3.0' ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Code Style Fixes
